[package]
name = "sitro"
version = "0.1.0"
edition = "2021"

[dependencies]
hayro = "0.4"
hayro-interpret = "0.4"
image = { version = "0.24.7", default-features = false, features = ["png"] }
imagesize = "0.12.0"
log = "0.4"
rayon = "1.8.1"
regex = "1.10.2"
tempdir = "0.3.7"
tiny-skia = "0.11.4"
walkdir = "2.4.0"
